### ISSUE TITLE
Intended support for the full unicode emoji list?

### ISSUE THREAD

**Issue by robinmetral** [streamich/emoji-json#2]
I'm definitely early to the party since this repo was just created yesterday :smile: 

Just wanted to know if you intended to support the full unicode emoji list (all [3019](https://www.unicode.org/emoji/charts/emoji-counts.html) of them). Looks like there's a bit under 1500 at the moment.

**Comment by streamich** [comment]
@robinmetral I'm not planning to add more in the immediate future, but PRs are welcome.

**Comment by robinmetral** [comment]
Thank you! Closing for now :slightly_smiling_face:
